module.exports = {
  types: [
    { value: 'feat', name: 'feat:       New consumer-facing feature' },
    { value: 'fix', name: 'fix:        Bug fix' },
    { value: 'perf', name: 'perf:       Performance improvement' },
    { value: 'refactor', name: 'refactor:   Internal refactor (no consumer impact)' },
    { value: 'chore', name: 'chore:      Build, tooling, or config' },
    { value: 'docs', name: 'docs:       Documentation only' },
    { value: 'test', name: 'test:       Tests only' },
    { value: 'ci', name: 'ci:         CI/CD changes' },
    { value: 'token', name: 'token:      Token change (consumer-facing)' },
    { value: 'component', name: 'component:  Component prop, slot, or event change' },
    { value: 'a11y', name: 'a11y:       Accessibility improvement (consumer-facing)' },
    { value: 'breaking', name: 'breaking:   Breaking change' },
  ],
  scopes: [
    { name: 'token/color' },
    { name: 'token/typography' },
    { name: 'token/spacing' },
    { name: 'token/motion' },
    { name: 'token/radius' },
    { name: 'token/breakpoint' },
    { name: 'token/prominence' },
    { name: 'cdr-button' },
    { name: 'cdr-input' },
    { name: 'cdr-modal' },
    { name: 'cdr-link' },
    { name: 'cdr-chip' },
    { name: 'cdr-accordion' },
    { name: 'cdr-table' },
    { name: 'cdr-tooltip' },
    { name: 'dist' },
    { name: 'types' },
    { name: 'imports' },
    { name: 'a11y' },
  ],
  messages: {
    type: 'What type of change is this?',
    scope: 'What is the scope? (token category or component name)',
    subject: 'Short description — imperative, lowercase, no period',
    body: 'Context for consumers (optional)',
    breaking: 'Describe the breaking change for consumers (blank if none)',
    footer: 'Reference tickets (optional)',
    confirmCommit: 'Confirm commit?',
  },
  allowBreakingChanges: ['feat', 'fix', 'token', 'component', 'breaking'],
  subjectLimit: 72,
};
