import type StyleDictionary from 'style-dictionary';
import type { FormatFnArguments, TransformedToken } from 'style-dictionary/types';

export const iosTextFormat = (sd: typeof StyleDictionary): void => {
  sd.registerFormat({
    name: 'ios/swift-text',
    format: ({ dictionary }: FormatFnArguments): string => {
      const textTokens = dictionary.allTokens.filter(
        (token: TransformedToken) => token.path[0] === 'text',
      );

      const lines = textTokens
        .map((token: TransformedToken) => {
          const name = token.name;
          const value = token.$value;

          if (token.$type === 'fontFamily') {
            return `    public static let ${name} = "${value}"`;
          }

          const numericVal = parseFloat(String(value).replace(/[a-zA-Z]/g, '')) || 0;
          return `    public static let ${name} = CGFloat(${numericVal.toFixed(1)})`;
        })
        .join('\n');

      return [
        '// Automatically generated by Cedar Token Pipeline',
        'import UIKit',
        '',
        'public struct CedarText {',
        lines,
        '}',
      ].join('\n');
    },
  });
};
