import fs from 'node:fs';
import path from 'node:path';

type TokenUsageMap = Record<string, string[]>;

const repoRoot = process.cwd();
const tokensGlobalDir = path.join(repoRoot, 'tokens', 'global');
const resolvedTokensPath = path.join(repoRoot, 'dist', 'rei-dot-com', 'json', 'global.json');
const generatedDir = path.join(repoRoot, 'stories', 'generated');
const generatedCssPath = path.join(generatedDir, 'storybook-design-tokens.css');
const generatedUsageMapPath = path.join(generatedDir, 'token-usage-map.ts');

type ResolvedToken = {
  name: string;
  value: string;
  category: string;
  presenter: string;
};

type DistToken = {
  name?: string;
  $value?: unknown;
};

function toTitleCase(input: string): string {
  return input
    .split('-')
    .filter(Boolean)
    .map((word) => word[0]!.toUpperCase() + word.slice(1))
    .join(' ');
}

function getComponentLabel(fileBaseName: string): string {
  const foundationNames = new Set([
    'color',
    'space',
    'radius',
    'prominence',
    'motion-duration',
    'motion-timing',
  ]);

  if (foundationNames.has(fileBaseName)) {
    return `${toTitleCase(fileBaseName)} Foundation`;
  }

  return toTitleCase(fileBaseName);
}

function getCategoryByTokenName(tokenName: string): string {
  if (tokenName.startsWith('cdr-color-') || tokenName.includes('-color-')) {
    return 'Colors';
  }

  if (tokenName.startsWith('cdr-space-')) {
    return 'Spacing';
  }

  if (tokenName.startsWith('cdr-radius-')) {
    return 'Border Radius';
  }

  if (
    tokenName.startsWith('cdr-duration-') ||
    tokenName.startsWith('cdr-timing-') ||
    tokenName.includes('motion')
  ) {
    return 'Motion';
  }

  if (
    tokenName.startsWith('cdr-font-') ||
    tokenName.startsWith('cdr-type-') ||
    tokenName.includes('typography') ||
    tokenName.includes('line-height') ||
    tokenName.includes('text-size')
  ) {
    return 'Typography';
  }

  return 'Other';
}

function getPresenterByCategory(category: string): string {
  if (category === 'Colors') return 'Color';
  if (category === 'Spacing') return 'Spacing';
  if (category === 'Border Radius') return 'BorderRadius';
  if (category === 'Motion') return 'Animation';
  if (category === 'Typography') return 'FontSize';
  return 'Spacing';
}

function normalizeValue(value: unknown): string {
  if (typeof value === 'string') {
    return value;
  }

  if (typeof value === 'number') {
    return `${value}`;
  }

  if (typeof value === 'boolean') {
    return value ? 'true' : 'false';
  }

  return '';
}

function toCssVarName(tokenPath: string[]): string {
  return `--cdr-${tokenPath.join('-')}`.replace(/--+/g, '--');
}

function collectResolvedTokens(node: unknown, collector: ResolvedToken[]): void {
  if (Array.isArray(node)) {
    for (const entry of node) {
      collectResolvedTokens(entry, collector);
    }
    return;
  }

  if (!node || typeof node !== 'object') {
    return;
  }

  const distToken = node as DistToken;
  if (typeof distToken.name === 'string') {
    const normalizedValue = normalizeValue(distToken.$value);
    if (normalizedValue) {
      const category = getCategoryByTokenName(distToken.name);
      collector.push({
        name: distToken.name,
        value: normalizedValue,
        category,
        presenter: getPresenterByCategory(category),
      });
    }
  }

  for (const value of Object.values(node)) {
    collectResolvedTokens(value, collector);
  }
}

function walkTokens(
  node: unknown,
  pathParts: string[],
  fileBaseName: string,
  usageMap: TokenUsageMap,
): void {
  if (!node || typeof node !== 'object') {
    return;
  }

  const tokenNode = node as Record<string, unknown>;

  if ('$value' in tokenNode) {
    const cssVarName = toCssVarName(pathParts);
    const componentLabel = getComponentLabel(fileBaseName);

    if (!usageMap[cssVarName]) {
      usageMap[cssVarName] = [];
    }

    if (!usageMap[cssVarName].includes(componentLabel)) {
      usageMap[cssVarName].push(componentLabel);
    }

    return;
  }

  for (const [key, value] of Object.entries(tokenNode)) {
    if (key.startsWith('$')) {
      continue;
    }

    walkTokens(value, [...pathParts, key], fileBaseName, usageMap);
  }
}

function buildDesignTokenCss(flatTokens: ResolvedToken[]): string {
  const categories = ['Colors', 'Spacing', 'Border Radius', 'Motion', 'Typography', 'Other'];

  const lines: string[] = [
    '/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */',
    '/* Generated by scripts/generate-storybook-token-docs.ts */',
    '',
    ':root {',
  ];

  for (const category of categories) {
    const categoryTokens = flatTokens.filter((token) => token.category === category);
    if (categoryTokens.length === 0) {
      continue;
    }

    const presenter = categoryTokens[0].presenter;

    lines.push('  /**');
    lines.push(`   * @tokens ${category}`);
    lines.push(`   * @presenter ${presenter}`);
    lines.push('   */');

    for (const token of categoryTokens) {
      const safeValue = token.value.replaceAll('\n', ' ').trim();
      lines.push(`  --${token.name}: ${safeValue};`);
    }

    lines.push('');
    lines.push('  /**');
    lines.push('   * @tokens-end');
    lines.push('   */');
    lines.push('');
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function buildUsageMapTs(usageMap: TokenUsageMap): string {
  const sortedEntries = Object.entries(usageMap)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([token, owners]) => [token, [...owners].sort((a, b) => a.localeCompare(b))]);

  return [
    '// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.',
    '// Generated by scripts/generate-storybook-token-docs.ts',
    '',
    'export type TokenUsageMap = Record<string, string[]>;',
    '',
    `export const tokenUsageMap: TokenUsageMap = ${JSON.stringify(Object.fromEntries(sortedEntries), null, 2)};`,
    '',
  ].join('\n');
}

function main(): void {
  if (!fs.existsSync(tokensGlobalDir)) {
    throw new Error(`Missing tokens directory: ${tokensGlobalDir}`);
  }

  if (!fs.existsSync(resolvedTokensPath)) {
    throw new Error(
      `Missing resolved token file: ${resolvedTokensPath}. Run 'pnpm run build:tokens' first.`,
    );
  }

  fs.mkdirSync(generatedDir, { recursive: true });

  const files = fs
    .readdirSync(tokensGlobalDir)
    .filter((fileName) => fileName.endsWith('.json'))
    .sort((a, b) => a.localeCompare(b));

  const flatTokens: ResolvedToken[] = [];
  const usageMap: TokenUsageMap = {};

  const resolvedTokensJson = JSON.parse(fs.readFileSync(resolvedTokensPath, 'utf-8')) as Record<
    string,
    unknown
  >;
  collectResolvedTokens(resolvedTokensJson, flatTokens);

  for (const fileName of files) {
    const filePath = path.join(tokensGlobalDir, fileName);
    const fileBaseName = fileName.replace(/\.json$/, '');
    const jsonData = JSON.parse(fs.readFileSync(filePath, 'utf-8')) as Record<string, unknown>;

    walkTokens(jsonData, [], fileBaseName, usageMap);
  }

  flatTokens.sort((a, b) => a.name.localeCompare(b.name));

  const cssOutput = buildDesignTokenCss(flatTokens);
  const usageMapOutput = buildUsageMapTs(usageMap);

  fs.writeFileSync(generatedCssPath, cssOutput, 'utf-8');
  fs.writeFileSync(generatedUsageMapPath, usageMapOutput, 'utf-8');

  process.stdout.write(
    `Generated token docs: ${flatTokens.length} tokens, ${Object.keys(usageMap).length} usage map entries\n`,
  );
}

main();
