import type { TransformedToken } from 'style-dictionary';
import StyleDictionary from 'style-dictionary';

StyleDictionary.registerFormat({
  name: 'android/compose-colors',
  format: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(
      (token: TransformedToken) => token.path[0] === 'color',
    );

    const colorProperties = colorTokens
      .map((token: TransformedToken) => {
        const camelName = token.name
          .split('_')
          .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
          .join('');
        const hexValue = (token.$value as string).replace('#', '0xFF');
        return `    val ${camelName} = Color(${hexValue})`;
      })
      .join('\n');

    return [
      '// Automatically generated by Cedar Token Pipeline - Android',
      '// Compose color schemes for Jetpack Compose',
      'package com.rei.cedar.tokens',
      '',
      'import androidx.compose.ui.graphics.Color',
      '',
      'object CedarColors {',
      colorProperties,
      '}',
    ].join('\n');
  },
});
