import type { TransformedToken } from 'style-dictionary';
import StyleDictionary from 'style-dictionary';

StyleDictionary.registerFormat({
  name: 'swift/spacing-static-struct',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens
      .map((token: TransformedToken) => {
        // Clear any text remnants (like px or rem) to safeguard raw float numbers
        const numericVal = parseFloat(String(token.$value).replace(/[a-zA-Z]/g, '')) || 0;

        // Formats path parts from ['spacing', 'space', 'sm'] -> 'spacingSpaceSm'
        const camelName = token.path
          .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
          .join('');

        return `    public static let ${camelName} = CGFloat(${numericVal})`;
      })
      .join('\n');

    return [
      '// Automatically generated by Cedar Token Pipeline Pipeline Spike',
      'import UIKit',
      'import Foundation',
      '',
      'public struct CdrSpacing {',
      lines,
      '}',
    ].join('\n');
  },
});
