import type { TransformedToken } from 'style-dictionary';
import StyleDictionary from 'style-dictionary';

function parseNumericValue(value: string | number) {
  return parseFloat(String(value).replace(/[a-zA-Z]/g, '')) || 0;
}

StyleDictionary.registerFormat({
  name: 'swift/text-size-struct',
  format: ({ dictionary }) => {
    let headingTitleLines: string = '';
    let headingSansLines: string = '';

    dictionary.allTokens.forEach((token: TransformedToken) => {
      token.$value = { ...token.$extensions.cedar.ios.light };

      if (token.path.includes('sans')) {
        const typography = token.$value;

        headingSansLines = [
          `  public static let fontSize: CGFloat = ${parseNumericValue(typography['fontSize'])}`,
          `  public static let lineHeight: CGFloat = ${parseNumericValue(
            typography['lineHeight'],
          )}`,
          `  public static let fontWeight: UIFont.Weight = ${parseNumericValue(
            typography['fontWeight'],
          )}`,
          `  public static let fontFamily: String = "${typography['fontFamily']}"`,
          `  public static let letterSpacing: CGFloat = ${parseNumericValue(
            typography['letterSpacing'],
          )}
        `,
        ].join('\n');
      } else {
        const typography = token.$value;

        headingTitleLines = [
          `  public static let fontSize: CGFloat = ${parseNumericValue(typography['fontSize'])}`,
          `  public static let lineHeight: CGFloat = ${parseNumericValue(
            typography['lineHeight'],
          )}`,
          `  public static let fontWeight: UIFont.Weight = ${parseNumericValue(
            typography['fontWeight'],
          )}`,
          `  public static let fontFamily: String = "${typography['fontFamily']}"`,
          `  public static let letterSpacing: CGFloat = ${parseNumericValue(
            typography['letterSpacing'],
          )}
        `,
        ].join('\n');
      }
    });

    return [
      '// Automatically generated by Cedar Token Pipeline Pipeline Spike',
      'import UIKit',
      'import Foundation',
      '',
      'public enum CdrTypography {',
      ' public enum HeadingSans {',
      headingSansLines,
      ' }',
      '',
      ' public enum Title {',
      headingTitleLines,
      ' }',
      '}',
    ].join('\n');
  },
});
