import type { TransformedToken } from 'style-dictionary';
import StyleDictionary from 'style-dictionary';

StyleDictionary.registerFormat({
  name: 'swift/extension-color',
  format: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(
      (token: TransformedToken) => token.path[0] === 'color',
    );

    const uiColorExtensions = colorTokens
      .map((token: TransformedToken) => {
        const camelName = token.name.charAt(0).toUpperCase() + token.name.slice(1);
        return `    public static let cdr${camelName} = UIColor(named: "cdr-${token.name}", in: Bundle.module, compatibleWith: nil)`;
      })
      .join('\n');

    const colorExtensions = colorTokens
      .map((token: TransformedToken) => {
        const camelName = token.name.charAt(0).toUpperCase() + token.name.slice(1);
        return `    public static let cdr${camelName} = Color("cdr-${token.name}", bundle: .module)`;
      })
      .join('\n');

    return [
      '// Automatically generated by Cedar Token Pipeline - Swift Package Manager',
      '// Swift extension-based color access for modern iOS projects',
      'import UIKit',
      'import SwiftUI',
      '',
      'extension UIColor {',
      uiColorExtensions,
      '}',
      '',
      'extension Color {',
      colorExtensions,
      '}',
    ].join('\n');
  },
});
